<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="DESKTOP-454JC8E" name="pytest" skipped="0" tests="4" time="0.073" timestamp="2019-12-19T22:12:08.071087"><testcase classname="Tests.test_space.Test_test_space" file="Tests\test_space.py" line="19" name="test_add_unit" time="0.002"></testcase><testcase classname="Tests.test_space.Test_test_space" file="Tests\test_space.py" line="34" name="test_check_collision" time="0.002"></testcase><testcase classname="Tests.test_space.Test_test_space" file="Tests\test_space.py" line="49" name="test_cleaning" time="0.002"><failure message="AssertionError: 10 != 1">self = &lt;Tests.test_space.Test_test_space testMethod=test_cleaning&gt;

    def test_cleaning(self):
        self.space.add_unit(MagicMock())
    
        self.space.cleaning()
    
&gt;       self.assertEqual(10, len(self.space.units))
E       AssertionError: 10 != 1

Tests\test_space.py:55: AssertionError</failure></testcase><testcase classname="Tests.test_space.Test_test_space" file="Tests\test_space.py" line="24" name="test_move_unit" time="0.002"></testcase></testsuite></testsuites>